//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.AssignedTeams = new HashSet<AssignedTeam>();
        }
    
        public decimal id { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<decimal> project_id { get; set; }
        public Nullable<double> rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedTeam> AssignedTeams { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
