//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public decimal Id { get; set; }
        public decimal team_id { get; set; }
        public decimal user_id { get; set; }
        public int rate { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
